[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
lifetime = "52XbisxVLPiSTV7voRXMkRjX31yw9XwZJJPQSi81tVkV"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/samuel.vanderwaal/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
